{"metadata":{"roleHeading":"Framework","symbolKind":"module","role":"collection","title":"PingOneWallet","modules":[{"name":"PingOneWallet"}],"externalID":"PingOneWallet"},"sections":[],"identifier":{"url":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","anchor":"Classes","generated":true,"identifiers":["doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialMatcherResult","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialUtils","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialsPresentation","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/DataRepository","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/EncryptedFilesHelper","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PingOneWalletClient","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PollingHelper","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PresentationMatcherResult","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PresentationRequest","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PresentationResult","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletEncryptedStorageManager"]},{"title":"Protocols","anchor":"Protocols","generated":true,"identifiers":["doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageErrorHandler","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageManagerContract","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletCallbackHandler","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletEvent"]},{"title":"Structures","anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/ClaimKeys","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CodableIgnore","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/IssuerMetadata","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PairingRequest","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PingOneRegion","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PushNotificationBody","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/RequestedKey","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageKeys","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageSecureKey","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/UnknownEvent","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletCredentialEvent","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletError","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletPairingEvent"]},{"title":"Functions","anchor":"Functions","generated":true,"identifiers":["doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/log(_:fileName:functionName:lineNumber:)","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/logLine(_:fileName:functionName:lineNumber:)","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/logattention(_:fileName:functionName:lineNumber:)","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/logerror(_:fileName:functionName:lineNumber:)"]},{"title":"Enumerations","anchor":"Enumerations","generated":true,"identifiers":["doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialAction","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialEventType","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PairingError","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageError","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletEventType","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletException","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletPairingEventType"]},{"title":"Extended Modules","anchor":"Extended-Modules","generated":true,"identifiers":["doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/DIDSDK","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/Swift"]}],"hierarchy":{"paths":[[]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonewallet"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonewallet"]}],"abstract":[{"type":"text","text":"This defines the usage and interfaces of the PingOne Wallet SDK for iOS to interact with PingOne credentialing services. The SDK provides for a user to receive, save, and share credentials for identification and verification purposes."}],"references":{"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PresentationResult":{"kind":"symbol","abstract":[{"text":"Result of a credential presentation","type":"text"}],"type":"topic","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PresentationResult","title":"PresentationResult","role":"symbol","url":"\/documentation\/pingonewallet\/presentationresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationResult","kind":"identifier"}],"navigatorTitle":[{"text":"PresentationResult","kind":"identifier"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/logLine(_:fileName:functionName:lineNumber:)":{"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/pingonewallet\/logline(_:filename:functionname:linenumber:)","title":"logLine(_:fileName:functionName:lineNumber:)","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/logLine(_:fileName:functionName:lineNumber:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"fileName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"functionName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"lineNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet":{"title":"PingOneWallet","url":"\/documentation\/pingonewallet","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet","kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"This defines the usage and interfaces of the PingOne Wallet SDK for iOS to interact with PingOne credentialing services. The SDK provides for a user to receive, save, and share credentials for identification and verification purposes."}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/WalletPairingEvent":{"kind":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletPairingEvent","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WalletPairingEvent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"WalletPairingEvent"}],"url":"\/documentation\/pingonewallet\/walletpairingevent","role":"symbol","abstract":[{"text":"Object representing a pairing event for wallet, returned as a param via ","type":"text"},{"code":"WalletCallbackHandler.handleEvent","type":"codeVoice"}],"title":"WalletPairingEvent","type":"topic"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/WalletEncryptedStorageManager":{"type":"topic","navigatorTitle":[{"text":"WalletEncryptedStorageManager","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WalletEncryptedStorageManager","kind":"identifier"}],"url":"\/documentation\/pingonewallet\/walletencryptedstoragemanager","role":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletEncryptedStorageManager","abstract":[{"type":"text","text":"Default implementation of StorageManager"}],"title":"WalletEncryptedStorageManager","kind":"symbol"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/RequestedKey":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestedKey"}],"abstract":[{"type":"text","text":"Object representing criteria for native presentation requests"}],"role":"symbol","title":"RequestedKey","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/RequestedKey","navigatorTitle":[{"kind":"identifier","text":"RequestedKey"}],"type":"topic","url":"\/documentation\/pingonewallet\/requestedkey"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/DataRepository":{"url":"\/documentation\/pingonewallet\/datarepository","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataRepository","kind":"identifier"}],"abstract":[{"type":"text","text":"Data Repository used by wallet to store application instances, credentials, revocation signatures etc."},{"type":"text","text":" "},{"type":"text","text":"Wallet automatically initializes "},{"isActive":true,"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/DataRepository","type":"reference"},{"type":"text","text":" with default imeplementation of "},{"isActive":true,"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageManagerContract","type":"reference"}],"kind":"symbol","navigatorTitle":[{"text":"DataRepository","kind":"identifier"}],"title":"DataRepository","type":"topic","role":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/DataRepository"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/CredentialsPresentation":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialsPresentation"}],"navigatorTitle":[{"kind":"identifier","text":"CredentialsPresentation"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialsPresentation","kind":"symbol","url":"\/documentation\/pingonewallet\/credentialspresentation","title":"CredentialsPresentation","abstract":[{"text":"Object representing the presentation payload for a presentation request","type":"text"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/CredentialEventType":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pingonewallet\/credentialeventtype","title":"CredentialEventType","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialEventType","abstract":[{"type":"text","text":"Event type for "},{"type":"reference","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletCredentialEvent","isActive":true}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialEventType"}],"navigatorTitle":[{"kind":"identifier","text":"CredentialEventType"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/CredentialUtils":{"url":"\/documentation\/pingonewallet\/credentialutils","navigatorTitle":[{"text":"CredentialUtils","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialUtils","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Credentials Utility class"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialUtils","title":"CredentialUtils"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/WalletError":{"title":"WalletError","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Object representing errors occurring in wallet, returned as a param via "},{"type":"codeVoice","code":"WalletCallbackHandler.handleEvent"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WalletError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"WalletError","kind":"identifier"}],"url":"\/documentation\/pingonewallet\/walleterror","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletError"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/StorageErrorHandler":{"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageErrorHandler","type":"topic","url":"\/documentation\/pingonewallet\/storageerrorhandler","abstract":[{"text":"Protocol to forward any errors that happen when using ","type":"text"},{"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageManagerContract","isActive":true,"type":"reference"}],"kind":"symbol","navigatorTitle":[{"text":"StorageErrorHandler","kind":"identifier"}],"title":"StorageErrorHandler","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StorageErrorHandler","kind":"identifier"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/WalletEventType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletEventType"}],"abstract":[{"type":"text","text":"Supported event types returned in "},{"type":"codeVoice","code":"WalletCallbackHandler.handleEvent"}],"url":"\/documentation\/pingonewallet\/walleteventtype","navigatorTitle":[{"kind":"identifier","text":"WalletEventType"}],"type":"topic","role":"symbol","title":"WalletEventType","kind":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletEventType"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PushNotificationBody":{"kind":"symbol","title":"PushNotificationBody","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotificationBody","kind":"identifier"}],"url":"\/documentation\/pingonewallet\/pushnotificationbody","type":"topic","role":"symbol","navigatorTitle":[{"text":"PushNotificationBody","kind":"identifier"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PushNotificationBody","abstract":[]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PollingHelper":{"kind":"symbol","title":"PollingHelper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PollingHelper","kind":"identifier"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PollingHelper","navigatorTitle":[{"text":"PollingHelper","kind":"identifier"}],"type":"topic","url":"\/documentation\/pingonewallet\/pollinghelper","role":"symbol","abstract":[{"type":"text","text":"Helper class to poll for an action, manages the polling events based on application lifecycle"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/IssuerMetadata":{"type":"topic","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/IssuerMetadata","title":"IssuerMetadata","navigatorTitle":[{"text":"IssuerMetadata","kind":"identifier"}],"url":"\/documentation\/pingonewallet\/issuermetadata","abstract":[{"text":"Object containing metadata for the credential issuer","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IssuerMetadata","kind":"identifier"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/StorageSecureKey":{"navigatorTitle":[{"text":"StorageSecureKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonewallet\/storagesecurekey","abstract":[],"type":"topic","title":"StorageSecureKey","role":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageSecureKey","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StorageSecureKey","kind":"identifier"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/StorageManagerContract":{"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageManagerContract","title":"StorageManagerContract","navigatorTitle":[{"kind":"identifier","text":"StorageManagerContract"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StorageManagerContract"}],"url":"\/documentation\/pingonewallet\/storagemanagercontract","kind":"symbol","abstract":[],"role":"symbol","type":"topic"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/ClaimKeys":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClaimKeys","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ClaimKeys","kind":"identifier"}],"role":"symbol","abstract":[],"title":"ClaimKeys","kind":"symbol","url":"\/documentation\/pingonewallet\/claimkeys","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/ClaimKeys"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/StorageError":{"navigatorTitle":[{"kind":"identifier","text":"StorageError"}],"abstract":[],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StorageError"}],"type":"topic","url":"\/documentation\/pingonewallet\/storageerror","kind":"symbol","title":"StorageError"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/UnknownEvent":{"kind":"symbol","title":"UnknownEvent","url":"\/documentation\/pingonewallet\/unknownevent","role":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/UnknownEvent","abstract":[{"type":"text","text":"Returned when SDK receives a secure message in an unknown format that it is unable to parse"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnknownEvent"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnknownEvent"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/StorageKeys":{"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/StorageKeys","url":"\/documentation\/pingonewallet\/storagekeys","navigatorTitle":[{"text":"StorageKeys","kind":"identifier"}],"title":"StorageKeys","kind":"symbol","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StorageKeys","kind":"identifier"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PresentationRequest":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationRequest","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PresentationRequest","kind":"identifier"}],"abstract":[{"text":"PresentationRequest received in ","type":"text"},{"code":"WalletCallbackHandler.handleCredentialRequest","type":"codeVoice"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PresentationRequest","url":"\/documentation\/pingonewallet\/presentationrequest","title":"PresentationRequest","kind":"symbol"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/WalletException":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"WalletException","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WalletException","kind":"identifier"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletException","abstract":[],"title":"WalletException","url":"\/documentation\/pingonewallet\/walletexception"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/WalletPairingEventType":{"navigatorTitle":[{"kind":"identifier","text":"WalletPairingEventType"}],"type":"topic","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletPairingEventType","abstract":[{"type":"text","text":"Pairing event type for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletPairingEvent"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletPairingEventType"}],"role":"symbol","url":"\/documentation\/pingonewallet\/walletpairingeventtype","title":"WalletPairingEventType"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PairingError":{"type":"topic","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PairingError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PairingError"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PairingError"}],"url":"\/documentation\/pingonewallet\/pairingerror","title":"PairingError","abstract":[{"type":"text","text":"Paring error returned in "},{"isActive":true,"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletPairingEvent","type":"reference"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PresentationMatcherResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationMatcherResult","kind":"identifier"}],"url":"\/documentation\/pingonewallet\/presentationmatcherresult","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PresentationMatcherResult","title":"PresentationMatcherResult","abstract":[{"type":"text","text":"Class representing list of matching credential for a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PresentationRequest"}],"navigatorTitle":[{"text":"PresentationMatcherResult","kind":"identifier"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/CodableIgnore":{"title":"CodableIgnore","url":"\/documentation\/pingonewallet\/codableignore","type":"topic","role":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CodableIgnore","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CodableIgnore","kind":"identifier"}],"navigatorTitle":[{"text":"CodableIgnore","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PairingRequest":{"abstract":[{"type":"text","text":"Object representing pairing request for a wallet"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PairingRequest","kind":"identifier"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PairingRequest","navigatorTitle":[{"text":"PairingRequest","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"PairingRequest","url":"\/documentation\/pingonewallet\/pairingrequest"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/EncryptedFilesHelper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncryptedFilesHelper"}],"abstract":[],"role":"symbol","url":"\/documentation\/pingonewallet\/encryptedfileshelper","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EncryptedFilesHelper"}],"title":"EncryptedFilesHelper","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/EncryptedFilesHelper"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/CredentialMatcherResult":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CredentialMatcherResult"}],"abstract":[{"type":"text","text":"Native presentation payload for a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PresentationRequest"}],"title":"CredentialMatcherResult","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialMatcherResult","url":"\/documentation\/pingonewallet\/credentialmatcherresult","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialMatcherResult"}]},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/logerror(_:fileName:functionName:lineNumber:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/pingonewallet\/logerror(_:filename:functionname:linenumber:)","abstract":[],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/logerror(_:fileName:functionName:lineNumber:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logerror"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"functionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lineNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"logerror(_:fileName:functionName:lineNumber:)","type":"topic"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/WalletEvent":{"url":"\/documentation\/pingonewallet\/walletevent","role":"symbol","abstract":[{"text":"Wallet events returned in ","type":"text"},{"code":"WalletCallbackHandler.handleEvent","type":"codeVoice"}],"title":"WalletEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"WalletEvent"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletEvent"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletEvent","type":"topic"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/WalletCredentialEvent":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Wallet Credential Event received in callbacks, can be used to ask the app to “update” an existing credential (save new credential and delete the reference credential, giving users the impression of an update)"}],"navigatorTitle":[{"text":"WalletCredentialEvent","kind":"identifier"}],"type":"topic","url":"\/documentation\/pingonewallet\/walletcredentialevent","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WalletCredentialEvent","kind":"identifier"}],"title":"WalletCredentialEvent","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletCredentialEvent"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/WalletCallbackHandler":{"title":"WalletCallbackHandler","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"WalletCallbackHandler"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletCallbackHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletCallbackHandler"}],"url":"\/documentation\/pingonewallet\/walletcallbackhandler","type":"topic"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PingOneWalletVersionString":{"url":"\/documentation\/pingonewallet\/pingonewalletversionstring","type":"topic","abstract":[{"text":"Project version string for PingOneWallet.","type":"text"}],"kind":"symbol","title":"PingOneWalletVersionString","fragments":[{"kind":"identifier","text":"PingOneWalletVersionString"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PingOneWalletVersionString","role":"symbol"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PingOneRegion":{"navigatorTitle":[{"text":"PingOneRegion","kind":"identifier"}],"abstract":[{"text":"Object representing supported PingOne regional domains","type":"text"}],"url":"\/documentation\/pingonewallet\/pingoneregion","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PingOneRegion","kind":"identifier"}],"title":"PingOneRegion","type":"topic","kind":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PingOneRegion"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/CredentialAction":{"title":"CredentialAction","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialAction","kind":"identifier"}],"abstract":[{"type":"text","text":"Requested action for "},{"isActive":true,"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/WalletCredentialEvent","type":"reference"}],"kind":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/CredentialAction","type":"topic","role":"symbol","navigatorTitle":[{"text":"CredentialAction","kind":"identifier"}],"url":"\/documentation\/pingonewallet\/credentialaction"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/Swift":{"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/Swift","title":"Swift","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/pingonewallet\/swift","role":"collection"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/DIDSDK":{"url":"\/documentation\/pingonewallet\/didsdk","title":"DIDSDK","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/DIDSDK","role":"collection","kind":"symbol","abstract":[],"type":"topic"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PingOneWalletVersionNumber":{"role":"symbol","kind":"symbol","title":"PingOneWalletVersionNumber","abstract":[{"type":"text","text":"Project version number for PingOneWallet."}],"type":"topic","fragments":[{"text":"PingOneWalletVersionNumber","kind":"identifier"}],"url":"\/documentation\/pingonewallet\/pingonewalletversionnumber","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PingOneWalletVersionNumber"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/log(_:fileName:functionName:lineNumber:)":{"title":"log(_:fileName:functionName:lineNumber:)","url":"\/documentation\/pingonewallet\/log(_:filename:functionname:linenumber:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"fileName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"functionName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"lineNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/log(_:fileName:functionName:lineNumber:)"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/logattention(_:fileName:functionName:lineNumber:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logattention","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"fileName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"functionName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"lineNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/logattention(_:fileName:functionName:lineNumber:)","title":"logattention(_:fileName:functionName:lineNumber:)","role":"symbol","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/pingonewallet\/logattention(_:filename:functionname:linenumber:)"},"doc://com.pingidentity.PingOneWallet/documentation/PingOneWallet/PingOneWalletClient":{"abstract":[{"type":"text","text":"Client class to interact with Credentials and manage Wallet"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PingOneWalletClient","kind":"identifier"}],"navigatorTitle":[{"text":"PingOneWalletClient","kind":"identifier"}],"url":"\/documentation\/pingonewallet\/pingonewalletclient","kind":"symbol","type":"topic","title":"PingOneWalletClient","identifier":"doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PingOneWalletClient"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"anchor":"Variables","title":"Variables","generated":true,"identifiers":["doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PingOneWalletVersionNumber","doc:\/\/com.pingidentity.PingOneWallet\/documentation\/PingOneWallet\/PingOneWalletVersionString"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}